---
abstract: 'Test and deeply test two number is approximate equality'
author:
  - 'tadegenban <tadegenban@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Approximate
requires:
  Test::Builder: 0
version: 0.008
